// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/ft12/v1/common.proto

package ft12v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChecksumMode int32

const (
	ChecksumMode_CHECKSUM_MODE_UNSPECIFIED ChecksumMode = 0
	ChecksumMode_CHECKSUM_MODE_SUM         ChecksumMode = 1
	ChecksumMode_CHECKSUM_MODE_CRC16       ChecksumMode = 2
)

// Enum value maps for ChecksumMode.
var (
	ChecksumMode_name = map[int32]string{
		0: "CHECKSUM_MODE_UNSPECIFIED",
		1: "CHECKSUM_MODE_SUM",
		2: "CHECKSUM_MODE_CRC16",
	}
	ChecksumMode_value = map[string]int32{
		"CHECKSUM_MODE_UNSPECIFIED": 0,
		"CHECKSUM_MODE_SUM":         1,
		"CHECKSUM_MODE_CRC16":       2,
	}
)

func (x ChecksumMode) Enum() *ChecksumMode {
	p := new(ChecksumMode)
	*p = x
	return p
}

func (x ChecksumMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChecksumMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ft12_v1_common_proto_enumTypes[0].Descriptor()
}

func (ChecksumMode) Type() protoreflect.EnumType {
	return &file_proto_ft12_v1_common_proto_enumTypes[0]
}

func (x ChecksumMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChecksumMode.Descriptor instead.
func (ChecksumMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{0}
}

type ServiceState int32

const (
	ServiceState_SERVICE_STATE_UNSPECIFIED ServiceState = 0
	ServiceState_SERVICE_STATE_STOPPED     ServiceState = 1
	ServiceState_SERVICE_STATE_RUNNING     ServiceState = 2
	ServiceState_SERVICE_STATE_DEGRADED    ServiceState = 3
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "SERVICE_STATE_UNSPECIFIED",
		1: "SERVICE_STATE_STOPPED",
		2: "SERVICE_STATE_RUNNING",
		3: "SERVICE_STATE_DEGRADED",
	}
	ServiceState_value = map[string]int32{
		"SERVICE_STATE_UNSPECIFIED": 0,
		"SERVICE_STATE_STOPPED":     1,
		"SERVICE_STATE_RUNNING":     2,
		"SERVICE_STATE_DEGRADED":    3,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ft12_v1_common_proto_enumTypes[1].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_proto_ft12_v1_common_proto_enumTypes[1]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{1}
}

type EventDirection int32

const (
	EventDirection_EVENT_DIRECTION_UNSPECIFIED EventDirection = 0
	EventDirection_EVENT_DIRECTION_RX          EventDirection = 1
	EventDirection_EVENT_DIRECTION_TX          EventDirection = 2
	EventDirection_EVENT_DIRECTION_SYSTEM      EventDirection = 3
	EventDirection_EVENT_DIRECTION_ERROR       EventDirection = 4
)

// Enum value maps for EventDirection.
var (
	EventDirection_name = map[int32]string{
		0: "EVENT_DIRECTION_UNSPECIFIED",
		1: "EVENT_DIRECTION_RX",
		2: "EVENT_DIRECTION_TX",
		3: "EVENT_DIRECTION_SYSTEM",
		4: "EVENT_DIRECTION_ERROR",
	}
	EventDirection_value = map[string]int32{
		"EVENT_DIRECTION_UNSPECIFIED": 0,
		"EVENT_DIRECTION_RX":          1,
		"EVENT_DIRECTION_TX":          2,
		"EVENT_DIRECTION_SYSTEM":      3,
		"EVENT_DIRECTION_ERROR":       4,
	}
)

func (x EventDirection) Enum() *EventDirection {
	p := new(EventDirection)
	*p = x
	return p
}

func (x EventDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ft12_v1_common_proto_enumTypes[2].Descriptor()
}

func (EventDirection) Type() protoreflect.EnumType {
	return &file_proto_ft12_v1_common_proto_enumTypes[2]
}

func (x EventDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventDirection.Descriptor instead.
func (EventDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{2}
}

type FrameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Direction     EventDirection         `protobuf:"varint,4,opt,name=direction,proto3,enum=ft12.v1.EventDirection" json:"direction,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,5,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	ChecksumMode  ChecksumMode           `protobuf:"varint,6,opt,name=checksum_mode,json=checksumMode,proto3,enum=ft12.v1.ChecksumMode" json:"checksum_mode,omitempty"`
	RawHex        string                 `protobuf:"bytes,7,opt,name=raw_hex,json=rawHex,proto3" json:"raw_hex,omitempty"`
	Command       string                 `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameEvent) Reset() {
	*x = FrameEvent{}
	mi := &file_proto_ft12_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameEvent) ProtoMessage() {}

func (x *FrameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameEvent.ProtoReflect.Descriptor instead.
func (*FrameEvent) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *FrameEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FrameEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FrameEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *FrameEvent) GetDirection() EventDirection {
	if x != nil {
		return x.Direction
	}
	return EventDirection_EVENT_DIRECTION_UNSPECIFIED
}

func (x *FrameEvent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *FrameEvent) GetChecksumMode() ChecksumMode {
	if x != nil {
		return x.ChecksumMode
	}
	return ChecksumMode_CHECKSUM_MODE_UNSPECIFIED
}

func (x *FrameEvent) GetRawHex() string {
	if x != nil {
		return x.RawHex
	}
	return ""
}

func (x *FrameEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *FrameEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FrameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRecentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentEventsRequest) Reset() {
	*x = GetRecentEventsRequest{}
	mi := &file_proto_ft12_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentEventsRequest) ProtoMessage() {}

func (x *GetRecentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*FrameEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentEventsResponse) Reset() {
	*x = GetRecentEventsResponse{}
	mi := &file_proto_ft12_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentEventsResponse) ProtoMessage() {}

func (x *GetRecentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentEventsResponse) GetEvents() []*FrameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_ft12_v1_common_proto protoreflect.FileDescriptor

const file_proto_ft12_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/ft12/v1/common.proto\x12\aft12.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x02\n" +
	"\n" +
	"FrameEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x125\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x17.ft12.v1.EventDirectionR\tdirection\x12\x1f\n" +
	"\vremote_addr\x18\x05 \x01(\tR\n" +
	"remoteAddr\x12:\n" +
	"\rchecksum_mode\x18\x06 \x01(\x0e2\x15.ft12.v1.ChecksumModeR\fchecksumMode\x12\x17\n" +
	"\araw_hex\x18\a \x01(\tR\x06rawHex\x12\x18\n" +
	"\acommand\x18\b \x01(\tR\acommand\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\".\n" +
	"\x16GetRecentEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"F\n" +
	"\x17GetRecentEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.ft12.v1.FrameEventR\x06events*]\n" +
	"\fChecksumMode\x12\x1d\n" +
	"\x19CHECKSUM_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHECKSUM_MODE_SUM\x10\x01\x12\x17\n" +
	"\x13CHECKSUM_MODE_CRC16\x10\x02*\x7f\n" +
	"\fServiceState\x12\x1d\n" +
	"\x19SERVICE_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERVICE_STATE_STOPPED\x10\x01\x12\x19\n" +
	"\x15SERVICE_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SERVICE_STATE_DEGRADED\x10\x03*\x98\x01\n" +
	"\x0eEventDirection\x12\x1f\n" +
	"\x1bEVENT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_DIRECTION_RX\x10\x01\x12\x16\n" +
	"\x12EVENT_DIRECTION_TX\x10\x02\x12\x1a\n" +
	"\x16EVENT_DIRECTION_SYSTEM\x10\x03\x12\x19\n" +
	"\x15EVENT_DIRECTION_ERROR\x10\x04BJZHgithub.com/dimbo1324/ttron-ttr20-time-r/internal/api/grpc/ft12/v1;ft12v1b\x06proto3"

var (
	file_proto_ft12_v1_common_proto_rawDescOnce sync.Once
	file_proto_ft12_v1_common_proto_rawDescData []byte
)

func file_proto_ft12_v1_common_proto_rawDescGZIP() []byte {
	file_proto_ft12_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_ft12_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_common_proto_rawDesc), len(file_proto_ft12_v1_common_proto_rawDesc)))
	})
	return file_proto_ft12_v1_common_proto_rawDescData
}

var file_proto_ft12_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_ft12_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ft12_v1_common_proto_goTypes = []any{
	(ChecksumMode)(0),               // 0: ft12.v1.ChecksumMode
	(ServiceState)(0),               // 1: ft12.v1.ServiceState
	(EventDirection)(0),             // 2: ft12.v1.EventDirection
	(*FrameEvent)(nil),              // 3: ft12.v1.FrameEvent
	(*GetRecentEventsRequest)(nil),  // 4: ft12.v1.GetRecentEventsRequest
	(*GetRecentEventsResponse)(nil), // 5: ft12.v1.GetRecentEventsResponse
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_proto_ft12_v1_common_proto_depIdxs = []int32{
	6, // 0: ft12.v1.FrameEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: ft12.v1.FrameEvent.direction:type_name -> ft12.v1.EventDirection
	0, // 2: ft12.v1.FrameEvent.checksum_mode:type_name -> ft12.v1.ChecksumMode
	3, // 3: ft12.v1.GetRecentEventsResponse.events:type_name -> ft12.v1.FrameEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ft12_v1_common_proto_init() }
func file_proto_ft12_v1_common_proto_init() {
	if File_proto_ft12_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_common_proto_rawDesc), len(file_proto_ft12_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ft12_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_ft12_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_ft12_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_ft12_v1_common_proto_msgTypes,
	}.Build()
	File_proto_ft12_v1_common_proto = out.File
	file_proto_ft12_v1_common_proto_goTypes = nil
	file_proto_ft12_v1_common_proto_depIdxs = nil
}
