// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/ft12/v1/emulator.proto

package ft12v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaultMode struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ResponseDelayMs            int64                  `protobuf:"varint,1,opt,name=response_delay_ms,json=responseDelayMs,proto3" json:"response_delay_ms,omitempty"`
	CorruptChecksum            bool                   `protobuf:"varint,2,opt,name=corrupt_checksum,json=corruptChecksum,proto3" json:"corrupt_checksum,omitempty"`
	CorruptChecksumProbability float64                `protobuf:"fixed64,3,opt,name=corrupt_checksum_probability,json=corruptChecksumProbability,proto3" json:"corrupt_checksum_probability,omitempty"`
	FragmentResponse           bool                   `protobuf:"varint,4,opt,name=fragment_response,json=fragmentResponse,proto3" json:"fragment_response,omitempty"`
	FragmentProbability        float64                `protobuf:"fixed64,5,opt,name=fragment_probability,json=fragmentProbability,proto3" json:"fragment_probability,omitempty"`
	FragmentDelayMs            int64                  `protobuf:"varint,6,opt,name=fragment_delay_ms,json=fragmentDelayMs,proto3" json:"fragment_delay_ms,omitempty"`
	NoResponse                 bool                   `protobuf:"varint,7,opt,name=no_response,json=noResponse,proto3" json:"no_response,omitempty"`
	CloseAfterRequest          bool                   `protobuf:"varint,8,opt,name=close_after_request,json=closeAfterRequest,proto3" json:"close_after_request,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *FaultMode) Reset() {
	*x = FaultMode{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultMode) ProtoMessage() {}

func (x *FaultMode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultMode.ProtoReflect.Descriptor instead.
func (*FaultMode) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{0}
}

func (x *FaultMode) GetResponseDelayMs() int64 {
	if x != nil {
		return x.ResponseDelayMs
	}
	return 0
}

func (x *FaultMode) GetCorruptChecksum() bool {
	if x != nil {
		return x.CorruptChecksum
	}
	return false
}

func (x *FaultMode) GetCorruptChecksumProbability() float64 {
	if x != nil {
		return x.CorruptChecksumProbability
	}
	return 0
}

func (x *FaultMode) GetFragmentResponse() bool {
	if x != nil {
		return x.FragmentResponse
	}
	return false
}

func (x *FaultMode) GetFragmentProbability() float64 {
	if x != nil {
		return x.FragmentProbability
	}
	return 0
}

func (x *FaultMode) GetFragmentDelayMs() int64 {
	if x != nil {
		return x.FragmentDelayMs
	}
	return 0
}

func (x *FaultMode) GetNoResponse() bool {
	if x != nil {
		return x.NoResponse
	}
	return false
}

func (x *FaultMode) GetCloseAfterRequest() bool {
	if x != nil {
		return x.CloseAfterRequest
	}
	return false
}

type EmulatorStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	State             ServiceState           `protobuf:"varint,1,opt,name=state,proto3,enum=ft12.v1.ServiceState" json:"state,omitempty"`
	ListenAddr        string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	ChecksumMode      ChecksumMode           `protobuf:"varint,3,opt,name=checksum_mode,json=checksumMode,proto3,enum=ft12.v1.ChecksumMode" json:"checksum_mode,omitempty"`
	ActiveConnections uint32                 `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalConnections  uint64                 `protobuf:"varint,5,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	TotalRequests     uint64                 `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalResponses    uint64                 `protobuf:"varint,7,opt,name=total_responses,json=totalResponses,proto3" json:"total_responses,omitempty"`
	ProtocolErrors    uint64                 `protobuf:"varint,8,opt,name=protocol_errors,json=protocolErrors,proto3" json:"protocol_errors,omitempty"`
	LastError         string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastRequestTime   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_request_time,json=lastRequestTime,proto3" json:"last_request_time,omitempty"`
	LastResponseTime  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_response_time,json=lastResponseTime,proto3" json:"last_response_time,omitempty"`
	FaultMode         *FaultMode             `protobuf:"bytes,12,opt,name=fault_mode,json=faultMode,proto3" json:"fault_mode,omitempty"`
	RecentFramesCount uint32                 `protobuf:"varint,13,opt,name=recent_frames_count,json=recentFramesCount,proto3" json:"recent_frames_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmulatorStatus) Reset() {
	*x = EmulatorStatus{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmulatorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmulatorStatus) ProtoMessage() {}

func (x *EmulatorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmulatorStatus.ProtoReflect.Descriptor instead.
func (*EmulatorStatus) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{1}
}

func (x *EmulatorStatus) GetState() ServiceState {
	if x != nil {
		return x.State
	}
	return ServiceState_SERVICE_STATE_UNSPECIFIED
}

func (x *EmulatorStatus) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *EmulatorStatus) GetChecksumMode() ChecksumMode {
	if x != nil {
		return x.ChecksumMode
	}
	return ChecksumMode_CHECKSUM_MODE_UNSPECIFIED
}

func (x *EmulatorStatus) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *EmulatorStatus) GetTotalConnections() uint64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *EmulatorStatus) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *EmulatorStatus) GetTotalResponses() uint64 {
	if x != nil {
		return x.TotalResponses
	}
	return 0
}

func (x *EmulatorStatus) GetProtocolErrors() uint64 {
	if x != nil {
		return x.ProtocolErrors
	}
	return 0
}

func (x *EmulatorStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *EmulatorStatus) GetLastRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequestTime
	}
	return nil
}

func (x *EmulatorStatus) GetLastResponseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastResponseTime
	}
	return nil
}

func (x *EmulatorStatus) GetFaultMode() *FaultMode {
	if x != nil {
		return x.FaultMode
	}
	return nil
}

func (x *EmulatorStatus) GetRecentFramesCount() uint32 {
	if x != nil {
		return x.RecentFramesCount
	}
	return 0
}

type GetEmulatorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmulatorStatusRequest) Reset() {
	*x = GetEmulatorStatusRequest{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmulatorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmulatorStatusRequest) ProtoMessage() {}

func (x *GetEmulatorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmulatorStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEmulatorStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{2}
}

type GetEmulatorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *EmulatorStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmulatorStatusResponse) Reset() {
	*x = GetEmulatorStatusResponse{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmulatorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmulatorStatusResponse) ProtoMessage() {}

func (x *GetEmulatorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmulatorStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEmulatorStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmulatorStatusResponse) GetStatus() *EmulatorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetFaultModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaultModeRequest) Reset() {
	*x = GetFaultModeRequest{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaultModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaultModeRequest) ProtoMessage() {}

func (x *GetFaultModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaultModeRequest.ProtoReflect.Descriptor instead.
func (*GetFaultModeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{4}
}

type GetFaultModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaultMode     *FaultMode             `protobuf:"bytes,1,opt,name=fault_mode,json=faultMode,proto3" json:"fault_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaultModeResponse) Reset() {
	*x = GetFaultModeResponse{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaultModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaultModeResponse) ProtoMessage() {}

func (x *GetFaultModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaultModeResponse.ProtoReflect.Descriptor instead.
func (*GetFaultModeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{5}
}

func (x *GetFaultModeResponse) GetFaultMode() *FaultMode {
	if x != nil {
		return x.FaultMode
	}
	return nil
}

type SetFaultModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaultMode     *FaultMode             `protobuf:"bytes,1,opt,name=fault_mode,json=faultMode,proto3" json:"fault_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFaultModeRequest) Reset() {
	*x = SetFaultModeRequest{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFaultModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFaultModeRequest) ProtoMessage() {}

func (x *SetFaultModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFaultModeRequest.ProtoReflect.Descriptor instead.
func (*SetFaultModeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{6}
}

func (x *SetFaultModeRequest) GetFaultMode() *FaultMode {
	if x != nil {
		return x.FaultMode
	}
	return nil
}

type SetFaultModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaultMode     *FaultMode             `protobuf:"bytes,1,opt,name=fault_mode,json=faultMode,proto3" json:"fault_mode,omitempty"`
	Status        *EmulatorStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFaultModeResponse) Reset() {
	*x = SetFaultModeResponse{}
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFaultModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFaultModeResponse) ProtoMessage() {}

func (x *SetFaultModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_emulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFaultModeResponse.ProtoReflect.Descriptor instead.
func (*SetFaultModeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_emulator_proto_rawDescGZIP(), []int{7}
}

func (x *SetFaultModeResponse) GetFaultMode() *FaultMode {
	if x != nil {
		return x.FaultMode
	}
	return nil
}

func (x *SetFaultModeResponse) GetStatus() *EmulatorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_ft12_v1_emulator_proto protoreflect.FileDescriptor

const file_proto_ft12_v1_emulator_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ft12/v1/emulator.proto\x12\aft12.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/ft12/v1/common.proto\"\x81\x03\n" +
	"\tFaultMode\x12*\n" +
	"\x11response_delay_ms\x18\x01 \x01(\x03R\x0fresponseDelayMs\x12)\n" +
	"\x10corrupt_checksum\x18\x02 \x01(\bR\x0fcorruptChecksum\x12@\n" +
	"\x1ccorrupt_checksum_probability\x18\x03 \x01(\x01R\x1acorruptChecksumProbability\x12+\n" +
	"\x11fragment_response\x18\x04 \x01(\bR\x10fragmentResponse\x121\n" +
	"\x14fragment_probability\x18\x05 \x01(\x01R\x13fragmentProbability\x12*\n" +
	"\x11fragment_delay_ms\x18\x06 \x01(\x03R\x0ffragmentDelayMs\x12\x1f\n" +
	"\vno_response\x18\a \x01(\bR\n" +
	"noResponse\x12.\n" +
	"\x13close_after_request\x18\b \x01(\bR\x11closeAfterRequest\"\x83\x05\n" +
	"\x0eEmulatorStatus\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.ft12.v1.ServiceStateR\x05state\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12:\n" +
	"\rchecksum_mode\x18\x03 \x01(\x0e2\x15.ft12.v1.ChecksumModeR\fchecksumMode\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\rR\x11activeConnections\x12+\n" +
	"\x11total_connections\x18\x05 \x01(\x04R\x10totalConnections\x12%\n" +
	"\x0etotal_requests\x18\x06 \x01(\x04R\rtotalRequests\x12'\n" +
	"\x0ftotal_responses\x18\a \x01(\x04R\x0etotalResponses\x12'\n" +
	"\x0fprotocol_errors\x18\b \x01(\x04R\x0eprotocolErrors\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12F\n" +
	"\x11last_request_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRequestTime\x12H\n" +
	"\x12last_response_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x10lastResponseTime\x121\n" +
	"\n" +
	"fault_mode\x18\f \x01(\v2\x12.ft12.v1.FaultModeR\tfaultMode\x12.\n" +
	"\x13recent_frames_count\x18\r \x01(\rR\x11recentFramesCount\"\x1a\n" +
	"\x18GetEmulatorStatusRequest\"L\n" +
	"\x19GetEmulatorStatusResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.ft12.v1.EmulatorStatusR\x06status\"\x15\n" +
	"\x13GetFaultModeRequest\"I\n" +
	"\x14GetFaultModeResponse\x121\n" +
	"\n" +
	"fault_mode\x18\x01 \x01(\v2\x12.ft12.v1.FaultModeR\tfaultMode\"H\n" +
	"\x13SetFaultModeRequest\x121\n" +
	"\n" +
	"fault_mode\x18\x01 \x01(\v2\x12.ft12.v1.FaultModeR\tfaultMode\"z\n" +
	"\x14SetFaultModeResponse\x121\n" +
	"\n" +
	"fault_mode\x18\x01 \x01(\v2\x12.ft12.v1.FaultModeR\tfaultMode\x12/\n" +
	"\x06status\x18\x02 \x01(\v2\x17.ft12.v1.EmulatorStatusR\x06status2\xd5\x02\n" +
	"\x0fEmulatorService\x12R\n" +
	"\tGetStatus\x12!.ft12.v1.GetEmulatorStatusRequest\x1a\".ft12.v1.GetEmulatorStatusResponse\x12K\n" +
	"\fGetFaultMode\x12\x1c.ft12.v1.GetFaultModeRequest\x1a\x1d.ft12.v1.GetFaultModeResponse\x12K\n" +
	"\fSetFaultMode\x12\x1c.ft12.v1.SetFaultModeRequest\x1a\x1d.ft12.v1.SetFaultModeResponse\x12T\n" +
	"\x0fGetRecentEvents\x12\x1f.ft12.v1.GetRecentEventsRequest\x1a .ft12.v1.GetRecentEventsResponseBJZHgithub.com/dimbo1324/ttron-ttr20-time-r/internal/api/grpc/ft12/v1;ft12v1b\x06proto3"

var (
	file_proto_ft12_v1_emulator_proto_rawDescOnce sync.Once
	file_proto_ft12_v1_emulator_proto_rawDescData []byte
)

func file_proto_ft12_v1_emulator_proto_rawDescGZIP() []byte {
	file_proto_ft12_v1_emulator_proto_rawDescOnce.Do(func() {
		file_proto_ft12_v1_emulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_emulator_proto_rawDesc), len(file_proto_ft12_v1_emulator_proto_rawDesc)))
	})
	return file_proto_ft12_v1_emulator_proto_rawDescData
}

var file_proto_ft12_v1_emulator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ft12_v1_emulator_proto_goTypes = []any{
	(*FaultMode)(nil),                 // 0: ft12.v1.FaultMode
	(*EmulatorStatus)(nil),            // 1: ft12.v1.EmulatorStatus
	(*GetEmulatorStatusRequest)(nil),  // 2: ft12.v1.GetEmulatorStatusRequest
	(*GetEmulatorStatusResponse)(nil), // 3: ft12.v1.GetEmulatorStatusResponse
	(*GetFaultModeRequest)(nil),       // 4: ft12.v1.GetFaultModeRequest
	(*GetFaultModeResponse)(nil),      // 5: ft12.v1.GetFaultModeResponse
	(*SetFaultModeRequest)(nil),       // 6: ft12.v1.SetFaultModeRequest
	(*SetFaultModeResponse)(nil),      // 7: ft12.v1.SetFaultModeResponse
	(ServiceState)(0),                 // 8: ft12.v1.ServiceState
	(ChecksumMode)(0),                 // 9: ft12.v1.ChecksumMode
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*GetRecentEventsRequest)(nil),    // 11: ft12.v1.GetRecentEventsRequest
	(*GetRecentEventsResponse)(nil),   // 12: ft12.v1.GetRecentEventsResponse
}
var file_proto_ft12_v1_emulator_proto_depIdxs = []int32{
	8,  // 0: ft12.v1.EmulatorStatus.state:type_name -> ft12.v1.ServiceState
	9,  // 1: ft12.v1.EmulatorStatus.checksum_mode:type_name -> ft12.v1.ChecksumMode
	10, // 2: ft12.v1.EmulatorStatus.last_request_time:type_name -> google.protobuf.Timestamp
	10, // 3: ft12.v1.EmulatorStatus.last_response_time:type_name -> google.protobuf.Timestamp
	0,  // 4: ft12.v1.EmulatorStatus.fault_mode:type_name -> ft12.v1.FaultMode
	1,  // 5: ft12.v1.GetEmulatorStatusResponse.status:type_name -> ft12.v1.EmulatorStatus
	0,  // 6: ft12.v1.GetFaultModeResponse.fault_mode:type_name -> ft12.v1.FaultMode
	0,  // 7: ft12.v1.SetFaultModeRequest.fault_mode:type_name -> ft12.v1.FaultMode
	0,  // 8: ft12.v1.SetFaultModeResponse.fault_mode:type_name -> ft12.v1.FaultMode
	1,  // 9: ft12.v1.SetFaultModeResponse.status:type_name -> ft12.v1.EmulatorStatus
	2,  // 10: ft12.v1.EmulatorService.GetStatus:input_type -> ft12.v1.GetEmulatorStatusRequest
	4,  // 11: ft12.v1.EmulatorService.GetFaultMode:input_type -> ft12.v1.GetFaultModeRequest
	6,  // 12: ft12.v1.EmulatorService.SetFaultMode:input_type -> ft12.v1.SetFaultModeRequest
	11, // 13: ft12.v1.EmulatorService.GetRecentEvents:input_type -> ft12.v1.GetRecentEventsRequest
	3,  // 14: ft12.v1.EmulatorService.GetStatus:output_type -> ft12.v1.GetEmulatorStatusResponse
	5,  // 15: ft12.v1.EmulatorService.GetFaultMode:output_type -> ft12.v1.GetFaultModeResponse
	7,  // 16: ft12.v1.EmulatorService.SetFaultMode:output_type -> ft12.v1.SetFaultModeResponse
	12, // 17: ft12.v1.EmulatorService.GetRecentEvents:output_type -> ft12.v1.GetRecentEventsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ft12_v1_emulator_proto_init() }
func file_proto_ft12_v1_emulator_proto_init() {
	if File_proto_ft12_v1_emulator_proto != nil {
		return
	}
	file_proto_ft12_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_emulator_proto_rawDesc), len(file_proto_ft12_v1_emulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ft12_v1_emulator_proto_goTypes,
		DependencyIndexes: file_proto_ft12_v1_emulator_proto_depIdxs,
		MessageInfos:      file_proto_ft12_v1_emulator_proto_msgTypes,
	}.Build()
	File_proto_ft12_v1_emulator_proto = out.File
	file_proto_ft12_v1_emulator_proto_goTypes = nil
	file_proto_ft12_v1_emulator_proto_depIdxs = nil
}
