// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/ft12/v1/emulator.proto

package ft12v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmulatorService_GetStatus_FullMethodName       = "/ft12.v1.EmulatorService/GetStatus"
	EmulatorService_GetFaultMode_FullMethodName    = "/ft12.v1.EmulatorService/GetFaultMode"
	EmulatorService_SetFaultMode_FullMethodName    = "/ft12.v1.EmulatorService/SetFaultMode"
	EmulatorService_GetRecentEvents_FullMethodName = "/ft12.v1.EmulatorService/GetRecentEvents"
)

// EmulatorServiceClient is the client API for EmulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmulatorServiceClient interface {
	GetStatus(ctx context.Context, in *GetEmulatorStatusRequest, opts ...grpc.CallOption) (*GetEmulatorStatusResponse, error)
	GetFaultMode(ctx context.Context, in *GetFaultModeRequest, opts ...grpc.CallOption) (*GetFaultModeResponse, error)
	SetFaultMode(ctx context.Context, in *SetFaultModeRequest, opts ...grpc.CallOption) (*SetFaultModeResponse, error)
	GetRecentEvents(ctx context.Context, in *GetRecentEventsRequest, opts ...grpc.CallOption) (*GetRecentEventsResponse, error)
}

type emulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmulatorServiceClient(cc grpc.ClientConnInterface) EmulatorServiceClient {
	return &emulatorServiceClient{cc}
}

func (c *emulatorServiceClient) GetStatus(ctx context.Context, in *GetEmulatorStatusRequest, opts ...grpc.CallOption) (*GetEmulatorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmulatorStatusResponse)
	err := c.cc.Invoke(ctx, EmulatorService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorServiceClient) GetFaultMode(ctx context.Context, in *GetFaultModeRequest, opts ...grpc.CallOption) (*GetFaultModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFaultModeResponse)
	err := c.cc.Invoke(ctx, EmulatorService_GetFaultMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorServiceClient) SetFaultMode(ctx context.Context, in *SetFaultModeRequest, opts ...grpc.CallOption) (*SetFaultModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFaultModeResponse)
	err := c.cc.Invoke(ctx, EmulatorService_SetFaultMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorServiceClient) GetRecentEvents(ctx context.Context, in *GetRecentEventsRequest, opts ...grpc.CallOption) (*GetRecentEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentEventsResponse)
	err := c.cc.Invoke(ctx, EmulatorService_GetRecentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmulatorServiceServer is the server API for EmulatorService service.
// All implementations must embed UnimplementedEmulatorServiceServer
// for forward compatibility.
type EmulatorServiceServer interface {
	GetStatus(context.Context, *GetEmulatorStatusRequest) (*GetEmulatorStatusResponse, error)
	GetFaultMode(context.Context, *GetFaultModeRequest) (*GetFaultModeResponse, error)
	SetFaultMode(context.Context, *SetFaultModeRequest) (*SetFaultModeResponse, error)
	GetRecentEvents(context.Context, *GetRecentEventsRequest) (*GetRecentEventsResponse, error)
	mustEmbedUnimplementedEmulatorServiceServer()
}

// UnimplementedEmulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmulatorServiceServer struct{}

func (UnimplementedEmulatorServiceServer) GetStatus(context.Context, *GetEmulatorStatusRequest) (*GetEmulatorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEmulatorServiceServer) GetFaultMode(context.Context, *GetFaultModeRequest) (*GetFaultModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFaultMode not implemented")
}
func (UnimplementedEmulatorServiceServer) SetFaultMode(context.Context, *SetFaultModeRequest) (*SetFaultModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFaultMode not implemented")
}
func (UnimplementedEmulatorServiceServer) GetRecentEvents(context.Context, *GetRecentEventsRequest) (*GetRecentEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentEvents not implemented")
}
func (UnimplementedEmulatorServiceServer) mustEmbedUnimplementedEmulatorServiceServer() {}
func (UnimplementedEmulatorServiceServer) testEmbeddedByValue()                         {}

// UnsafeEmulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmulatorServiceServer will
// result in compilation errors.
type UnsafeEmulatorServiceServer interface {
	mustEmbedUnimplementedEmulatorServiceServer()
}

func RegisterEmulatorServiceServer(s grpc.ServiceRegistrar, srv EmulatorServiceServer) {
	// If the following call panics, it indicates UnimplementedEmulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmulatorService_ServiceDesc, srv)
}

func _EmulatorService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmulatorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServiceServer).GetStatus(ctx, req.(*GetEmulatorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorService_GetFaultMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFaultModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServiceServer).GetFaultMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorService_GetFaultMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServiceServer).GetFaultMode(ctx, req.(*GetFaultModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorService_SetFaultMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFaultModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServiceServer).SetFaultMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorService_SetFaultMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServiceServer).SetFaultMode(ctx, req.(*SetFaultModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorService_GetRecentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServiceServer).GetRecentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorService_GetRecentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServiceServer).GetRecentEvents(ctx, req.(*GetRecentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmulatorService_ServiceDesc is the grpc.ServiceDesc for EmulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ft12.v1.EmulatorService",
	HandlerType: (*EmulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _EmulatorService_GetStatus_Handler,
		},
		{
			MethodName: "GetFaultMode",
			Handler:    _EmulatorService_GetFaultMode_Handler,
		},
		{
			MethodName: "SetFaultMode",
			Handler:    _EmulatorService_SetFaultMode_Handler,
		},
		{
			MethodName: "GetRecentEvents",
			Handler:    _EmulatorService_GetRecentEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ft12/v1/emulator.proto",
}
