// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/ft12/v1/gateway.proto

package ft12v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetStatus_FullMethodName       = "/ft12.v1.GatewayService/GetStatus"
	GatewayService_StartPolling_FullMethodName    = "/ft12.v1.GatewayService/StartPolling"
	GatewayService_StopPolling_FullMethodName     = "/ft12.v1.GatewayService/StopPolling"
	GatewayService_GetRecentEvents_FullMethodName = "/ft12.v1.GatewayService/GetRecentEvents"
	GatewayService_GetLastReadTime_FullMethodName = "/ft12.v1.GatewayService/GetLastReadTime"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetStatus(ctx context.Context, in *GetGatewayStatusRequest, opts ...grpc.CallOption) (*GetGatewayStatusResponse, error)
	StartPolling(ctx context.Context, in *StartPollingRequest, opts ...grpc.CallOption) (*StartPollingResponse, error)
	StopPolling(ctx context.Context, in *StopPollingRequest, opts ...grpc.CallOption) (*StopPollingResponse, error)
	GetRecentEvents(ctx context.Context, in *GetRecentEventsRequest, opts ...grpc.CallOption) (*GetRecentEventsResponse, error)
	GetLastReadTime(ctx context.Context, in *GetLastReadTimeRequest, opts ...grpc.CallOption) (*GetLastReadTimeResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetStatus(ctx context.Context, in *GetGatewayStatusRequest, opts ...grpc.CallOption) (*GetGatewayStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayStatusResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StartPolling(ctx context.Context, in *StartPollingRequest, opts ...grpc.CallOption) (*StartPollingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPollingResponse)
	err := c.cc.Invoke(ctx, GatewayService_StartPolling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StopPolling(ctx context.Context, in *StopPollingRequest, opts ...grpc.CallOption) (*StopPollingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPollingResponse)
	err := c.cc.Invoke(ctx, GatewayService_StopPolling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRecentEvents(ctx context.Context, in *GetRecentEventsRequest, opts ...grpc.CallOption) (*GetRecentEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentEventsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetRecentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetLastReadTime(ctx context.Context, in *GetLastReadTimeRequest, opts ...grpc.CallOption) (*GetLastReadTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastReadTimeResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetLastReadTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetStatus(context.Context, *GetGatewayStatusRequest) (*GetGatewayStatusResponse, error)
	StartPolling(context.Context, *StartPollingRequest) (*StartPollingResponse, error)
	StopPolling(context.Context, *StopPollingRequest) (*StopPollingResponse, error)
	GetRecentEvents(context.Context, *GetRecentEventsRequest) (*GetRecentEventsResponse, error)
	GetLastReadTime(context.Context, *GetLastReadTimeRequest) (*GetLastReadTimeResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetStatus(context.Context, *GetGatewayStatusRequest) (*GetGatewayStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGatewayServiceServer) StartPolling(context.Context, *StartPollingRequest) (*StartPollingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPolling not implemented")
}
func (UnimplementedGatewayServiceServer) StopPolling(context.Context, *StopPollingRequest) (*StopPollingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPolling not implemented")
}
func (UnimplementedGatewayServiceServer) GetRecentEvents(context.Context, *GetRecentEventsRequest) (*GetRecentEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentEvents not implemented")
}
func (UnimplementedGatewayServiceServer) GetLastReadTime(context.Context, *GetLastReadTimeRequest) (*GetLastReadTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastReadTime not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetStatus(ctx, req.(*GetGatewayStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StartPolling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPollingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).StartPolling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_StartPolling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).StartPolling(ctx, req.(*StartPollingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StopPolling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPollingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).StopPolling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_StopPolling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).StopPolling(ctx, req.(*StopPollingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRecentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRecentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRecentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRecentEvents(ctx, req.(*GetRecentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetLastReadTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastReadTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetLastReadTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetLastReadTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetLastReadTime(ctx, req.(*GetLastReadTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ft12.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _GatewayService_GetStatus_Handler,
		},
		{
			MethodName: "StartPolling",
			Handler:    _GatewayService_StartPolling_Handler,
		},
		{
			MethodName: "StopPolling",
			Handler:    _GatewayService_StopPolling_Handler,
		},
		{
			MethodName: "GetRecentEvents",
			Handler:    _GatewayService_GetRecentEvents_Handler,
		},
		{
			MethodName: "GetLastReadTime",
			Handler:    _GatewayService_GetLastReadTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ft12/v1/gateway.proto",
}
