// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/ft12/v1/gateway.proto

package ft12v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	State                  ServiceState           `protobuf:"varint,1,opt,name=state,proto3,enum=ft12.v1.ServiceState" json:"state,omitempty"`
	TargetAddr             string                 `protobuf:"bytes,2,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`
	ChecksumMode           ChecksumMode           `protobuf:"varint,3,opt,name=checksum_mode,json=checksumMode,proto3,enum=ft12.v1.ChecksumMode" json:"checksum_mode,omitempty"`
	PollingIntervalMs      int64                  `protobuf:"varint,4,opt,name=polling_interval_ms,json=pollingIntervalMs,proto3" json:"polling_interval_ms,omitempty"`
	RequestTimeoutMs       int64                  `protobuf:"varint,5,opt,name=request_timeout_ms,json=requestTimeoutMs,proto3" json:"request_timeout_ms,omitempty"`
	ConnectTimeoutMs       int64                  `protobuf:"varint,6,opt,name=connect_timeout_ms,json=connectTimeoutMs,proto3" json:"connect_timeout_ms,omitempty"`
	Connected              bool                   `protobuf:"varint,7,opt,name=connected,proto3" json:"connected,omitempty"`
	ConnectionAttempts     uint64                 `protobuf:"varint,8,opt,name=connection_attempts,json=connectionAttempts,proto3" json:"connection_attempts,omitempty"`
	SuccessfulReads        uint64                 `protobuf:"varint,9,opt,name=successful_reads,json=successfulReads,proto3" json:"successful_reads,omitempty"`
	FailedReads            uint64                 `protobuf:"varint,10,opt,name=failed_reads,json=failedReads,proto3" json:"failed_reads,omitempty"`
	Reconnects             uint64                 `protobuf:"varint,11,opt,name=reconnects,proto3" json:"reconnects,omitempty"`
	LastSuccessfulReadTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_successful_read_time,json=lastSuccessfulReadTime,proto3" json:"last_successful_read_time,omitempty"`
	LastDeviceTime         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_device_time,json=lastDeviceTime,proto3" json:"last_device_time,omitempty"`
	LastError              string                 `protobuf:"bytes,14,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastTxTime             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_tx_time,json=lastTxTime,proto3" json:"last_tx_time,omitempty"`
	LastRxTime             *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_rx_time,json=lastRxTime,proto3" json:"last_rx_time,omitempty"`
	RecentFramesCount      uint32                 `protobuf:"varint,17,opt,name=recent_frames_count,json=recentFramesCount,proto3" json:"recent_frames_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayStatus) GetState() ServiceState {
	if x != nil {
		return x.State
	}
	return ServiceState_SERVICE_STATE_UNSPECIFIED
}

func (x *GatewayStatus) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *GatewayStatus) GetChecksumMode() ChecksumMode {
	if x != nil {
		return x.ChecksumMode
	}
	return ChecksumMode_CHECKSUM_MODE_UNSPECIFIED
}

func (x *GatewayStatus) GetPollingIntervalMs() int64 {
	if x != nil {
		return x.PollingIntervalMs
	}
	return 0
}

func (x *GatewayStatus) GetRequestTimeoutMs() int64 {
	if x != nil {
		return x.RequestTimeoutMs
	}
	return 0
}

func (x *GatewayStatus) GetConnectTimeoutMs() int64 {
	if x != nil {
		return x.ConnectTimeoutMs
	}
	return 0
}

func (x *GatewayStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GatewayStatus) GetConnectionAttempts() uint64 {
	if x != nil {
		return x.ConnectionAttempts
	}
	return 0
}

func (x *GatewayStatus) GetSuccessfulReads() uint64 {
	if x != nil {
		return x.SuccessfulReads
	}
	return 0
}

func (x *GatewayStatus) GetFailedReads() uint64 {
	if x != nil {
		return x.FailedReads
	}
	return 0
}

func (x *GatewayStatus) GetReconnects() uint64 {
	if x != nil {
		return x.Reconnects
	}
	return 0
}

func (x *GatewayStatus) GetLastSuccessfulReadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessfulReadTime
	}
	return nil
}

func (x *GatewayStatus) GetLastDeviceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDeviceTime
	}
	return nil
}

func (x *GatewayStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GatewayStatus) GetLastTxTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTxTime
	}
	return nil
}

func (x *GatewayStatus) GetLastRxTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRxTime
	}
	return nil
}

func (x *GatewayStatus) GetRecentFramesCount() uint32 {
	if x != nil {
		return x.RecentFramesCount
	}
	return 0
}

type GetGatewayStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayStatusRequest) Reset() {
	*x = GetGatewayStatusRequest{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayStatusRequest) ProtoMessage() {}

func (x *GetGatewayStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{1}
}

type GetGatewayStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *GatewayStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayStatusResponse) Reset() {
	*x = GetGatewayStatusResponse{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayStatusResponse) ProtoMessage() {}

func (x *GetGatewayStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetGatewayStatusResponse) GetStatus() *GatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StartPollingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPollingRequest) Reset() {
	*x = StartPollingRequest{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPollingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPollingRequest) ProtoMessage() {}

func (x *StartPollingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPollingRequest.ProtoReflect.Descriptor instead.
func (*StartPollingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type StartPollingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *GatewayStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPollingResponse) Reset() {
	*x = StartPollingResponse{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPollingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPollingResponse) ProtoMessage() {}

func (x *StartPollingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPollingResponse.ProtoReflect.Descriptor instead.
func (*StartPollingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *StartPollingResponse) GetStatus() *GatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopPollingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPollingRequest) Reset() {
	*x = StopPollingRequest{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPollingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPollingRequest) ProtoMessage() {}

func (x *StopPollingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPollingRequest.ProtoReflect.Descriptor instead.
func (*StopPollingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{5}
}

type StopPollingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *GatewayStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPollingResponse) Reset() {
	*x = StopPollingResponse{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPollingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPollingResponse) ProtoMessage() {}

func (x *StopPollingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPollingResponse.ProtoReflect.Descriptor instead.
func (*StopPollingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *StopPollingResponse) GetStatus() *GatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetLastReadTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastReadTimeRequest) Reset() {
	*x = GetLastReadTimeRequest{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastReadTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastReadTimeRequest) ProtoMessage() {}

func (x *GetLastReadTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastReadTimeRequest.ProtoReflect.Descriptor instead.
func (*GetLastReadTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{7}
}

type GetLastReadTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=device_time,json=deviceTime,proto3" json:"device_time,omitempty"`
	ReadTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastReadTimeResponse) Reset() {
	*x = GetLastReadTimeResponse{}
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastReadTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastReadTimeResponse) ProtoMessage() {}

func (x *GetLastReadTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ft12_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastReadTimeResponse.ProtoReflect.Descriptor instead.
func (*GetLastReadTimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ft12_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GetLastReadTimeResponse) GetDeviceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeviceTime
	}
	return nil
}

func (x *GetLastReadTimeResponse) GetReadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadTime
	}
	return nil
}

func (x *GetLastReadTimeResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_proto_ft12_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_ft12_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ft12/v1/gateway.proto\x12\aft12.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/ft12/v1/common.proto\"\xca\x06\n" +
	"\rGatewayStatus\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.ft12.v1.ServiceStateR\x05state\x12\x1f\n" +
	"\vtarget_addr\x18\x02 \x01(\tR\n" +
	"targetAddr\x12:\n" +
	"\rchecksum_mode\x18\x03 \x01(\x0e2\x15.ft12.v1.ChecksumModeR\fchecksumMode\x12.\n" +
	"\x13polling_interval_ms\x18\x04 \x01(\x03R\x11pollingIntervalMs\x12,\n" +
	"\x12request_timeout_ms\x18\x05 \x01(\x03R\x10requestTimeoutMs\x12,\n" +
	"\x12connect_timeout_ms\x18\x06 \x01(\x03R\x10connectTimeoutMs\x12\x1c\n" +
	"\tconnected\x18\a \x01(\bR\tconnected\x12/\n" +
	"\x13connection_attempts\x18\b \x01(\x04R\x12connectionAttempts\x12)\n" +
	"\x10successful_reads\x18\t \x01(\x04R\x0fsuccessfulReads\x12!\n" +
	"\ffailed_reads\x18\n" +
	" \x01(\x04R\vfailedReads\x12\x1e\n" +
	"\n" +
	"reconnects\x18\v \x01(\x04R\n" +
	"reconnects\x12U\n" +
	"\x19last_successful_read_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x16lastSuccessfulReadTime\x12D\n" +
	"\x10last_device_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0elastDeviceTime\x12\x1d\n" +
	"\n" +
	"last_error\x18\x0e \x01(\tR\tlastError\x12<\n" +
	"\flast_tx_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastTxTime\x12<\n" +
	"\flast_rx_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastRxTime\x12.\n" +
	"\x13recent_frames_count\x18\x11 \x01(\rR\x11recentFramesCount\"\x19\n" +
	"\x17GetGatewayStatusRequest\"J\n" +
	"\x18GetGatewayStatusResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.ft12.v1.GatewayStatusR\x06status\"\x15\n" +
	"\x13StartPollingRequest\"F\n" +
	"\x14StartPollingResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.ft12.v1.GatewayStatusR\x06status\"\x14\n" +
	"\x12StopPollingRequest\"E\n" +
	"\x13StopPollingResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.ft12.v1.GatewayStatusR\x06status\"\x18\n" +
	"\x16GetLastReadTimeRequest\"\xad\x01\n" +
	"\x17GetLastReadTimeResponse\x12;\n" +
	"\vdevice_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deviceTime\x127\n" +
	"\tread_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\breadTime\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable2\xa5\x03\n" +
	"\x0eGatewayService\x12P\n" +
	"\tGetStatus\x12 .ft12.v1.GetGatewayStatusRequest\x1a!.ft12.v1.GetGatewayStatusResponse\x12K\n" +
	"\fStartPolling\x12\x1c.ft12.v1.StartPollingRequest\x1a\x1d.ft12.v1.StartPollingResponse\x12H\n" +
	"\vStopPolling\x12\x1b.ft12.v1.StopPollingRequest\x1a\x1c.ft12.v1.StopPollingResponse\x12T\n" +
	"\x0fGetRecentEvents\x12\x1f.ft12.v1.GetRecentEventsRequest\x1a .ft12.v1.GetRecentEventsResponse\x12T\n" +
	"\x0fGetLastReadTime\x12\x1f.ft12.v1.GetLastReadTimeRequest\x1a .ft12.v1.GetLastReadTimeResponseBJZHgithub.com/dimbo1324/ttron-ttr20-time-r/internal/api/grpc/ft12/v1;ft12v1b\x06proto3"

var (
	file_proto_ft12_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_ft12_v1_gateway_proto_rawDescData []byte
)

func file_proto_ft12_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_ft12_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_ft12_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_gateway_proto_rawDesc), len(file_proto_ft12_v1_gateway_proto_rawDesc)))
	})
	return file_proto_ft12_v1_gateway_proto_rawDescData
}

var file_proto_ft12_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ft12_v1_gateway_proto_goTypes = []any{
	(*GatewayStatus)(nil),            // 0: ft12.v1.GatewayStatus
	(*GetGatewayStatusRequest)(nil),  // 1: ft12.v1.GetGatewayStatusRequest
	(*GetGatewayStatusResponse)(nil), // 2: ft12.v1.GetGatewayStatusResponse
	(*StartPollingRequest)(nil),      // 3: ft12.v1.StartPollingRequest
	(*StartPollingResponse)(nil),     // 4: ft12.v1.StartPollingResponse
	(*StopPollingRequest)(nil),       // 5: ft12.v1.StopPollingRequest
	(*StopPollingResponse)(nil),      // 6: ft12.v1.StopPollingResponse
	(*GetLastReadTimeRequest)(nil),   // 7: ft12.v1.GetLastReadTimeRequest
	(*GetLastReadTimeResponse)(nil),  // 8: ft12.v1.GetLastReadTimeResponse
	(ServiceState)(0),                // 9: ft12.v1.ServiceState
	(ChecksumMode)(0),                // 10: ft12.v1.ChecksumMode
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*GetRecentEventsRequest)(nil),   // 12: ft12.v1.GetRecentEventsRequest
	(*GetRecentEventsResponse)(nil),  // 13: ft12.v1.GetRecentEventsResponse
}
var file_proto_ft12_v1_gateway_proto_depIdxs = []int32{
	9,  // 0: ft12.v1.GatewayStatus.state:type_name -> ft12.v1.ServiceState
	10, // 1: ft12.v1.GatewayStatus.checksum_mode:type_name -> ft12.v1.ChecksumMode
	11, // 2: ft12.v1.GatewayStatus.last_successful_read_time:type_name -> google.protobuf.Timestamp
	11, // 3: ft12.v1.GatewayStatus.last_device_time:type_name -> google.protobuf.Timestamp
	11, // 4: ft12.v1.GatewayStatus.last_tx_time:type_name -> google.protobuf.Timestamp
	11, // 5: ft12.v1.GatewayStatus.last_rx_time:type_name -> google.protobuf.Timestamp
	0,  // 6: ft12.v1.GetGatewayStatusResponse.status:type_name -> ft12.v1.GatewayStatus
	0,  // 7: ft12.v1.StartPollingResponse.status:type_name -> ft12.v1.GatewayStatus
	0,  // 8: ft12.v1.StopPollingResponse.status:type_name -> ft12.v1.GatewayStatus
	11, // 9: ft12.v1.GetLastReadTimeResponse.device_time:type_name -> google.protobuf.Timestamp
	11, // 10: ft12.v1.GetLastReadTimeResponse.read_time:type_name -> google.protobuf.Timestamp
	1,  // 11: ft12.v1.GatewayService.GetStatus:input_type -> ft12.v1.GetGatewayStatusRequest
	3,  // 12: ft12.v1.GatewayService.StartPolling:input_type -> ft12.v1.StartPollingRequest
	5,  // 13: ft12.v1.GatewayService.StopPolling:input_type -> ft12.v1.StopPollingRequest
	12, // 14: ft12.v1.GatewayService.GetRecentEvents:input_type -> ft12.v1.GetRecentEventsRequest
	7,  // 15: ft12.v1.GatewayService.GetLastReadTime:input_type -> ft12.v1.GetLastReadTimeRequest
	2,  // 16: ft12.v1.GatewayService.GetStatus:output_type -> ft12.v1.GetGatewayStatusResponse
	4,  // 17: ft12.v1.GatewayService.StartPolling:output_type -> ft12.v1.StartPollingResponse
	6,  // 18: ft12.v1.GatewayService.StopPolling:output_type -> ft12.v1.StopPollingResponse
	13, // 19: ft12.v1.GatewayService.GetRecentEvents:output_type -> ft12.v1.GetRecentEventsResponse
	8,  // 20: ft12.v1.GatewayService.GetLastReadTime:output_type -> ft12.v1.GetLastReadTimeResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_ft12_v1_gateway_proto_init() }
func file_proto_ft12_v1_gateway_proto_init() {
	if File_proto_ft12_v1_gateway_proto != nil {
		return
	}
	file_proto_ft12_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ft12_v1_gateway_proto_rawDesc), len(file_proto_ft12_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ft12_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_ft12_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_ft12_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_ft12_v1_gateway_proto = out.File
	file_proto_ft12_v1_gateway_proto_goTypes = nil
	file_proto_ft12_v1_gateway_proto_depIdxs = nil
}
